'use strict';
(()=>{const el=id=>document.getElementById(id);let store,sources=[],deleted=null,incoming=null;const selected=new Set();const today=()=>{const d=new Date();return new Date(d.getTime()-d.getTimezoneOffset()*60000).toISOString().slice(0,10);};const say=t=>el('status').textContent=t;function reset(){el('fault-form').reset();el('record-id').value='';el('date').value=today();}
function read(){if(!store)throw Error('Browser storage is unavailable. Records cannot be saved here.');return store.read();}
function render(){try{const list=el('fault-list');list.replaceChildren();const data=read();const query=el('unit-filter').value.toLowerCase();let count=0;for(const f of [...data.faults].sort((a,b)=>b.observedOn.localeCompare(a.observedOn))){if(el('filter').value!=='all'&&f.status!==el('filter').value)continue;if(query&&![f.unitSnapshot?.name,f.brand,f.model,f.code].join(' ').toLowerCase().includes(query))continue;if(el('from-date').value&&f.observedOn<el('from-date').value)continue;if(el('to-date').value&&f.observedOn>el('to-date').value)continue;count++;const card=document.createElement('article');card.className='result';const label=document.createElement('label'),check=document.createElement('input');check.type='checkbox';check.checked=selected.has(f.id);check.addEventListener('change',()=>check.checked?selected.add(f.id):selected.delete(f.id));label.append(check,document.createTextNode('Select for report'));card.append(label);const h=document.createElement('h2');h.textContent=(f.code||'Symptom record')+' · '+f.brand;card.append(h);for(const t of [f.model,(f.unitSnapshot?.name||'Unnamed unit')+' · '+f.observedOn+' · '+f.status,'Symptoms: '+f.symptoms,'Work notes: '+f.workNotes,'Resolution: '+f.resolution]){const p=document.createElement('p');p.textContent=t;card.append(p);}const tools=document.createElement('div');tools.className='tools';const edit=document.createElement('button');edit.textContent='Edit';edit.addEventListener('click',()=>{el('record-id').value=f.id;el('source').value=f.sourceId;el('unit').value=f.unitSnapshot?.name||'';el('serial').value=f.unitSnapshot?.serialNumber||'';el('date').value=f.observedOn;el('fault-status').value=f.status;el('code').value=f.code;el('symptoms').value=f.symptoms;el('work-notes').value=f.workNotes;el('resolution').value=f.resolution;el('resolved-on').value=f.resolvedOn||'';el('source').focus();});const remove=document.createElement('button');remove.textContent='Delete';remove.addEventListener('click',()=>{if(!confirm('Delete this fault record? You can undo the most recent deletion.'))return;try{deleted=store.removeFault(f.id);selected.delete(f.id);el('undo').hidden=false;render();say('Record deleted. Undo is available until the next deletion or page reload.');}catch(e){say(e.message);}});tools.append(edit,remove);card.append(tools);list.append(card);}if(!count){const p=document.createElement('p');p.textContent=data.faults.length?'No records match these filters.':'No faults saved yet.';list.append(p);}}catch(e){say(e.message);}}
el('fault-form').addEventListener('submit',async event=>{event.preventDefault();if(el('save-fault').disabled)return;try{const source=sources.find(s=>s.id===el('source').value);if(!source)throw Error('Select a brand/model.');if(!el('code').value.trim()&&!el('symptoms').value.trim())throw Error('Enter an error code or symptoms.');if(el('fault-status').value==='resolved'&&(!el('resolution').value.trim()||!el('resolved-on').value))throw Error('Add a resolution and resolved date.');if(el('resolved-on').value&&el('resolved-on').value<el('date').value)throw Error('Resolved date cannot precede the observed date.');const previous=read().faults.find(f=>f.id===el('record-id').value);const now=new Date().toISOString();const values=Object.fromEntries(['unit','serial','code','symptoms','date','fault-status','work-notes','resolution','resolved-on'].map(id=>[id,el(id).value.trim()]));el('save-fault').disabled=true;let evidence=[];try{const rows=await PumpSources.codes(source);evidence=rows.filter(r=>values['code']&&PumpSources.codeMatches(r.errorCode,values['code'])).map(r=>({rowId:r.rowId,code:r.errorCode,meaning:r.errorMeaning,documentedRemedy:r.possibleSolution,citation:PumpSources.citation(r)}));}catch(e){/* Recording a fault remains useful when its source cannot load. */}const f={id:previous?.id||crypto.randomUUID(),sourceId:source.id,brand:source.brand,model:source.label,unitSnapshot:{name:values['unit'],serialNumber:values['serial']},code:values['code'],symptoms:values['symptoms'],observedOn:values['date'],status:values['fault-status'],workNotes:values['work-notes'],resolution:values['resolution'],resolvedOn:values['fault-status']==='resolved'?values['resolved-on']:'',sourceSnapshots:evidence,createdAt:previous?.createdAt||now,updatedAt:now};store.saveFault(f);reset();render();say('Fault saved in this browser.'+(evidence.length?' Source evidence included.':' No code evidence attached.'));}catch(e){say(e.message);}finally{el('save-fault').disabled=false;}});
el('cancel-edit').addEventListener('click',reset);for(const id of ['filter','unit-filter','from-date','to-date'])el(id).addEventListener('input',render);
el('undo').addEventListener('click',()=>{if(!deleted)return;try{store.saveFault(deleted);deleted=null;el('undo').hidden=true;render();say('Deletion undone.');}catch(e){say(e.message);}});
el('export').addEventListener('click',()=>{try{const blob=new Blob([store.export()],{type:'application/json'}),url=URL.createObjectURL(blob),a=document.createElement('a');a.href=url;a.download='jamie-air-to-water-backup-'+today()+'.json';a.click();setTimeout(()=>URL.revokeObjectURL(url),1000);say('Backup download prepared.');}catch(e){say(e.message);}});
el('import-file').addEventListener('change',async()=>{try{const file=el('import-file').files[0];if(!file)return;if(file.size>10000000)throw Error('Backup is too large.');incoming=store.parseBackup(await file.text());const old=read();const duplicates=incoming.faults.filter(f=>old.faults.some(x=>x.id===f.id)).length;el('import-summary').textContent=incoming.faults.length+' incoming fault records; '+duplicates+' existing IDs will be kept unchanged. Units and favourites will also merge by ID.';el('import-preview').hidden=false;}catch(e){incoming=null;el('import-preview').hidden=true;say('Import rejected: '+e.message);}});
el('merge').addEventListener('click',()=>{try{if(!incoming)return;store.merge(incoming);incoming=null;el('import-preview').hidden=true;el('import-file').value='';render();say('Backup merged; existing records were preserved.');}catch(e){say(e.message);}});el('cancel-import').addEventListener('click',()=>{incoming=null;el('import-preview').hidden=true;el('import-file').value='';});
el('print').addEventListener('click',()=>{if(!selected.size){say('Select at least one fault for the report.');return;}location.href='report.html?ids='+encodeURIComponent([...selected].join(','));});
try{store=PumpStore.create(localStorage);store.read();}catch(e){say(e.message);store=null;}
reset();render();PumpSources.sources().then(list=>{sources=list;for(const s of list)el('source').add(new Option(s.brand+' — '+s.label,s.id));const params=new URLSearchParams(location.search),source=params.get('sourceId');if(source&&list.some(s=>s.id===source)){el('source').value=source;el('code').value=params.get('code')||'';}}).catch(()=>say('Could not load model sources. Refresh to retry.'));
})();
