(function(root){
'use strict';const KEY='jamie-air-to-water-v1';const empty=()=>({schemaVersion:1,units:[],faults:[],favourites:[]});
function validate(data){if(!data||data.schemaVersion!==1)throw Error('Unsupported backup version');for(const key of ['units','faults','favourites']){if(!Array.isArray(data[key])||data[key].length>10000)throw Error('Invalid '+key);const ids=new Set();for(const row of data[key]){if(!row||typeof row.id!=='string'||ids.has(row.id))throw Error('Missing or duplicate record ID');ids.add(row.id);}}
for(const f of data.faults){for(const k of ['brand','model','code','symptoms','observedOn','status','workNotes','resolution'])if(typeof f[k]!=='string'||f[k].length>10000)throw Error('Invalid fault field: '+k);if(!['open','resolved'].includes(f.status)||!/^\d{4}-\d{2}-\d{2}$/.test(f.observedOn))throw Error('Invalid fault status/date');const validDate=v=>{if(!/^\d{4}-\d{2}-\d{2}$/.test(v))return false;const d=new Date(v+'T00:00:00Z');return Number.isFinite(d.getTime())&&d.toISOString().slice(0,10)===v;};if(!validDate(f.observedOn))throw Error('Invalid observed date');if(f.status==='resolved'&&(!f.resolution||!validDate(f.resolvedOn)||f.resolvedOn<f.observedOn))throw Error('Invalid resolution date');if(f.unitSnapshot&&(!['name','serialNumber'].every(k=>typeof f.unitSnapshot[k]==='string')))throw Error('Invalid unit snapshot');if(f.sourceSnapshots&&!Array.isArray(f.sourceSnapshots))throw Error('Invalid source evidence');if(!f.brand||!f.model||(!f.code&&!f.symptoms))throw Error('Incomplete fault');}return data;}
function create(storage){let locked=false;function read(){try{const raw=storage.getItem(KEY);return raw?validate(JSON.parse(raw)):empty();}catch(e){locked=true;throw Error('Saved data could not be read. It has not been overwritten. Restore a valid backup or inspect browser storage.');}}
function write(data){if(locked)throw Error('Storage is locked after a read failure; existing data has been preserved.');validate(data);try{storage.setItem(KEY,JSON.stringify(data));}catch(e){throw Error('Could not save. Browser storage may be unavailable or full.');}return data;}
return {read,write,saveFault(fault){const data=read(),i=data.faults.findIndex(f=>f.id===fault.id);if(i<0)data.faults.push(fault);else data.faults[i]=fault;return write(data);},removeFault(id){const data=read();const row=data.faults.find(f=>f.id===id);data.faults=data.faults.filter(f=>f.id!==id);write(data);return row;},export(){return JSON.stringify({...read(),exportedAt:new Date().toISOString()},null,2);},parseBackup(text){if(text.length>10000000)throw Error('Backup is too large');return validate(JSON.parse(text));},merge(incoming){const data=read();for(const key of ['units','faults','favourites']){const ids=new Set(data[key].map(x=>x.id));for(const row of incoming[key])if(!ids.has(row.id))data[key].push(row);}return write(data);}};}
const api={create,validate,empty};if(typeof module!=='undefined')module.exports=api;else root.PumpStore=api;
})(typeof window!=='undefined'?window:globalThis);
